import { ShowItem, ArtistItem } from '../types';
import { EXTRA_ARTISTS, EXTRA_SHOWS } from './expandedSamples';

export const SAMPLE_SHOWS: ShowItem[] = [
  ...EXTRA_SHOWS,
  {
    id: 'show_001',
    showCode: 'LIVVO_COLDPLAY_SP',
    artistCode: 'coldplay',
    artistName: 'Coldplay',
    tourName: 'Music of the Spheres World Tour',
    venue: 'Estádio do Morumbi',
    city: 'São Paulo',
    state: 'SP',
    date: '18/03/2023',
    posterUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_002',
    showCode: 'LIVVO_TAYLOR_RIO',
    artistCode: 'taylor_swift',
    artistName: 'Taylor Swift',
    tourName: 'The Eras Tour',
    venue: 'Estádio Nilton Santos (Engenhão)',
    city: 'Rio de Janeiro',
    state: 'RJ',
    date: '19/11/2023',
    posterUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_003',
    showCode: 'LIVVO_TITAS_BH',
    artistCode: 'titas',
    artistName: 'Titãs',
    tourName: 'Titãs Encontro - Pra Dizer Adeus',
    venue: 'Arena MRV',
    city: 'Belo Horizonte',
    state: 'MG',
    date: '25/11/2023',
    posterUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_004',
    showCode: 'LIVVO_BRUNO_CURITIBA',
    artistCode: 'bruno_mars',
    artistName: 'Bruno Mars',
    tourName: 'Live in Brazil Tour',
    venue: 'Estádio Couto Pereira',
    city: 'Curitiba',
    state: 'PR',
    date: '31/10/2024',
    posterUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_005',
    showCode: 'LIVVO_IVETE_SSA',
    artistCode: 'ivete_sangalo',
    artistName: 'Ivete Sangalo',
    tourName: 'Ivete 30 Anos - Esquenta',
    venue: 'Arena Fonte Nova',
    city: 'Salvador',
    state: 'BA',
    date: '20/12/2023',
    posterUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_006',
    showCode: 'LIVVO_FOOFIGHTERS_SP',
    artistCode: 'foo_fighters',
    artistName: 'Foo Fighters',
    tourName: 'The Town Festival',
    venue: 'Autódromo de Interlagos',
    city: 'São Paulo',
    state: 'SP',
    date: '09/09/2023',
    posterUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_007',
    showCode: 'LIVVO_PAUL_POA',
    artistCode: 'paul_mccartney',
    artistName: 'Paul McCartney',
    tourName: 'Got Back Tour',
    venue: 'Estádio Beira-Rio',
    city: 'Porto Alegre',
    state: 'RS',
    date: '14/12/2023',
    posterUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80',
  },
  {
    id: 'show_008',
    showCode: 'LIVVO_LUDMILLA_RECIFE',
    artistCode: 'ludmilla',
    artistName: 'Ludmilla',
    tourName: 'Numanice Tour 3.0',
    venue: 'Parque Memorial Arcoverde',
    city: 'Recife',
    state: 'PE',
    date: '13/04/2024',
    posterUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80',
  },
];

export const SAMPLE_ARTISTS_DATA: ArtistItem[] = [
  ...EXTRA_ARTISTS,
  {
    artistCode: 'coldplay',
    artistName: 'Coldplay',
    showsCount: 1,
    photoUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1000&q=80',
    photoSource: 'sample',
  },
  {
    artistCode: 'taylor_swift',
    artistName: 'Taylor Swift',
    showsCount: 1,
    photoUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=1000&q=80',
    photoSource: 'sample',
  },
  {
    artistCode: 'titas',
    artistName: 'Titãs',
    showsCount: 1,
    photoUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1000&q=80',
    photoSource: 'sample',
  },
  {
    artistCode: 'bruno_mars',
    artistName: 'Bruno Mars',
    showsCount: 1,
    photoUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80',
    photoSource: 'sample',
  },
  {
    artistCode: 'ivete_sangalo',
    artistName: 'Ivete Sangalo',
    showsCount: 1,
    photoUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1000&q=80',
    photoSource: 'sample',
  },
];

export function generateSampleDataset(): { shows: ShowItem[]; artists: ArtistItem[] } {
  return {
    shows: SAMPLE_SHOWS,
    artists: SAMPLE_ARTISTS_DATA,
  };
}
